// Code generated by protoc-gen-go.
// source: playstore.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	playstore.proto

It has these top-level messages:
	Request
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Request struct {
	ProjectId         int32  `protobuf:"varint,3,opt,name=project_id" json:"project_id,omitempty"`
	InappPurchaseData string `protobuf:"bytes,1,opt,name=inapp_purchase_data" json:"inapp_purchase_data,omitempty"`
	Signature         string `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto1.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

type Response struct {
	Status    int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Options   string `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	ProductId string `protobuf:"bytes,3,opt,name=product_id" json:"product_id,omitempty"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for GoogleIapService service

type GoogleIapServiceClient interface {
	GooglePayVerify(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type googleIapServiceClient struct {
	cc *grpc.ClientConn
}

func NewGoogleIapServiceClient(cc *grpc.ClientConn) GoogleIapServiceClient {
	return &googleIapServiceClient{cc}
}

func (c *googleIapServiceClient) GooglePayVerify(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.GoogleIapService/GooglePayVerify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoogleIapService service

type GoogleIapServiceServer interface {
	GooglePayVerify(context.Context, *Request) (*Response, error)
}

func RegisterGoogleIapServiceServer(s *grpc.Server, srv GoogleIapServiceServer) {
	s.RegisterService(&_GoogleIapService_serviceDesc, srv)
}

func _GoogleIapService_GooglePayVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GoogleIapServiceServer).GooglePayVerify(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _GoogleIapService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GoogleIapService",
	HandlerType: (*GoogleIapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GooglePayVerify",
			Handler:    _GoogleIapService_GooglePayVerify_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}
